### PR TITLE
Adding ability to pull based on commit / hash

### LINKED ISSUE #48: spython pull if newer version available, otherwise ignore
Hey @vsoch,

I looked into this a bit myself, but wasn't able to find out if what I'm looking for is possible: basically, for the `Client.pull` method (https://github.com/singularityhub/singularity-cli/blob/master/spython/main/pull.py), is it possible to to have the following logic:

1. If the image has already been pulled and is the latest version, do nothing.
2. If the image has already been pulled and is the latest version, pull the image and overwrite the existing image.
3. If the image has not already been pulled, pull the image.

Thank you! (and keep up the great work :smiley:)

### PR DESCRIPTION
**Pull request by vsoch**
This will fix #48 to add the missing --commit and --pull flags to the client.

### CODE REVIEW

**Comment by mwiens91** [comment]
I'll look into this more when I have more time, but trying out this branch on Python3 with a basic script

```python
#!/usr/bin/env python3

from spython.main import Client

Client.pull(
    'shub://mwiens91/shub-debug',
    pull_folder='/home/matt/temp',
    name_by_commit=True,
)
```

Resulted in

```
singularity pull --commit shub://mwiens91/shub-debug
Traceback (most recent call last):
  File "singularity_pull_test.py", line 8, in <module>
    name_by_commit=True,
  File "/home/matt/.virtualenvs/asdf/local/lib/python3.6/site-packages/spython-0.0.42-py3.6.egg/spython/main/pull.py", line 94, in pull
    final_image = os.path.join(pull_folder, name)
  File "/home/matt/.virtualenvs/asdf/lib/python3.6/posixpath.py", line 94, in join
    genericpath._check_arg_types('join', a, *p)
  File "/home/matt/.virtualenvs/asdf/lib/python3.6/genericpath.py", line 149, in _check_arg_types
    (funcname, s.__class__.__name__)) from None
TypeError: join() argument must be str or bytes, not 'NoneType'
```

Regular pulling seems to work fine, though.

**Comment by vsoch** [comment]
okay I think I fixed the issue! Here is what I just did:

```python
from spython.main import Client

Client.pull(
    'shub://mwiens91/shub-debug',
    pull_folder='/tmp',
    name_by_commit=True,
)

## -- End pasted text --
singularity pull --commit shub://mwiens91/shub-debug
Progress |===================================| 100.0% 
Done. Container is at: /tmp/d13898a106f9678c695ab479335e285c634d3686.simg
Progress |===================================| 100.0% 
Done. Container is at: /tmp/d13898a106f9678c695ab479335e285c634d3686.simg
/tmp/d13898a106f9678c695ab479335e285c634d3686.simg
```
Let me know if it works for you!

**Comment by mwiens91** [comment]
Hmm. I'm getting another error:

```
singularity pull --commit shub://mwiens91/shub-debug
Progress |===================================| 100.0% 
Done. Container is at: /home/matt/temp/d13898a106f9678c695ab479335e285c634d3686.simg
Progress |===================================| 100.0% 
Done. Container is at: /home/matt/temp/d13898a106f9678c695ab479335e285c634d3686.simg
ERROR  : Called singularity_config_get_value on uninitialized config subsystem
ABORT  : Retval = 255
ERROR  : Called singularity_config_get_value on uninitialized config subsystem
ABORT  : Retval = 255

Traceback (most recent call last):
  File "singularity_pull_test.py", line 8, in <module>
    name_by_commit=True,
  File "/home/matt/.virtualenvs/asdf/local/lib/python3.6/site-packages/spython-0.0.42-py3.6.egg/spython/main/pull.py", line 103, in pull
    final_image = output.split('Container is at:')[-1].strip('\n').strip()
AttributeError: 'tuple' object has no attribute 'split'
```

It seems to be pulling twice?? Not sure what to make of it.

**Comment by vsoch** [comment]
Hrm I am seeing the error from Singularity - what version of Singularity do you have? I think the issue is that there is a Singularity error that then returns output that is unexpected, and it can't be parsed to return the container name.

**Comment by mwiens91** [comment]
```
$ singularity --version
2.4.2-dist
```

This the version provided by default in Ubuntu 18.04.

**Comment by vsoch** [comment]
I don't think ubuntu has a default version? Anyway, could you please update? That is a very old version (and one with security issues too, I think).

**Comment by mwiens91** [comment]
Yeah I'll try updating.

https://launchpad.net/ubuntu/+source/singularity-container

is what Ubuntu provides, btw.

**Comment by vsoch** [comment]
Oh I see, maybe 2.5.2 isn't specified for your distribution? --> https://launchpad.net/ubuntu/+source/singularity-container/2.5.2-2

**Comment by mwiens91** [comment]
Hmmm. I upgraded to 2.5.2 and am still getting the same error.

```
singularity pull --commit shub://mwiens91/shub-debug
Progress |===================================| 100.0% 
Done. Container is at: /home/matt/temp/d13898a106f9678c695ab479335e285c634d3686.simg
Progress |===================================| 100.0% 
Done. Container is at: /home/matt/temp/d13898a106f9678c695ab479335e285c634d3686.simg
ERROR  : Called singularity_config_get_value on uninitialized config subsystem
ABORT  : Retval = 255
ERROR  : Called singularity_config_get_value on uninitialized config subsystem
ABORT  : Retval = 255

Traceback (most recent call last):
  File "./singularity_pull_test.py", line 8, in <module>
    name_by_commit=True,
  File "/home/matt/.virtualenvs/asdf/local/lib/python3.6/site-packages/spython-0.0.42-py3.6.egg/spython/main/pull.py", line 103, in pull
    final_image = output.split('Container is at:')[-1].strip('\n').strip()
AttributeError: 'tuple' object has no attribute 'split'
```

Maybe I need to initialize my "config subsystem" (whatever that may mean)?

**Comment by vsoch** [comment]
Interesting I'm looking at the differences in the command now, and it comes down to having capture=True (to get the image name)

```
output = self._run_command(cmd, capture=True)
```
vs

```
# capture is False
self._run_command(cmd, capture=capture)
```
If you report that regular pull works and this one doesn't, then this is the issue - capturing the output. If the above doesn't work I have a workaround I think :)

**Comment by vsoch** [comment]
and I would bet we installed singularity differently to get the different functionality - maybe you did disable suid?

**Comment by mwiens91** [comment]
For Singularity 2.4.2 I just did a regular Ubuntu

```
sudo apt install singularity-container
```

with no other modification past that. Upgrading to Singularity 2.5.2, I used the package archive at Debian Neuroscience here:

http://neuro.debian.net/pkgs/singularity-container.html

and upgraded with apt again:

```
sudo apt upgrade
```

Again, with no further modification.

I haven't tried building from source on my main machine (package managers are nice :smile:), although I believe I have done so on a few VMs.

**Comment by vsoch** [comment]
okay I just a modification that should make the pull work as the one that you say is working... fingers crossed! It works for me still.

**Comment by vsoch** [comment]
See https://github.com/singularityhub/singularity-cli/pull/53/commits/6d0d25d646936b73a8666b25c1b12760cf7524d9

The workaround is to pull (without capture) to a temporary folder, and then move to the final spot and clean up.

**Comment by vsoch** [comment]
And I'm definitely terrible, I didn't even know we had an official package on there, heh :)

**Comment by mwiens91** [comment]
Yeah it definitely is to do with the package. I switched one of my Travis builds from building Singularity from source to getting Singularity from the Debian Neuroscience package repository, and the error popped up after making that change (it was absent before).

Before:
https://travis-ci.com/mwiens91/saltant/jobs/143532296#L3274

After:
https://travis-ci.com/mwiens91/saltant/jobs/144609969#L1055

**Comment by vsoch** [comment]
okay, I'm good integrating this and we will hope to resolve the neurodebian issue on the other thread. Merging!

**Comment by vsoch** [comment]
Here you go @mwiens91 thanks for your help with this! https://pypi.org/project/spython/ https://pypi.org/project/spython/0.0.42/

**Pull request merged**
