### PR TITLE
adding install step to the README.md

### PR DESCRIPTION
**Pull request by remyd1**
Just adding an "Install" step in the README.md

### CODE REVIEW

**Comment by vsoch** [comment]
oh good idea! Did you see the page [here](https://github.com/singularityhub/singularity-cli/blob/master/docs/pages/install.md)? Should we merge those two instructions (I didn't mention python 3) and put the link to the page in the README? I think the rendered page would be here --> https://singularityhub.github.io/singularity-cli/install

**Comment by remyd1** [comment]
Hi @vsoch 

No, I think did not see this page before (or I don't remember).
I agree we should merge all these informations.

Kind regards,
Rémy

**Comment by remyd1** [comment]
https://github.com/singularityhub/singularity-cli/pull/19

**Comment by vsoch** [comment]
All fixed up. Thanks again @remyd1

**Comment by Firedrops** [comment]
I couldn't find the install instructions until I found this closed issue. Please consider adding it into the main Readme file?

**Comment by vsoch** [comment]
done!

**Pull request closed without merging**
