### PR TITLE
fixing bug with instance stop all

### LINKED ISSUE #86: instance_stopall not stopping instances
## Expected Behavior

instance_stopall should stop all running instances.

## Actual Behavior

instance_stopall is not stopping any instances, getting a return code of 0

Tried using the command line of singularity using the command ``singularity instance stop --all`` to verify that stopping was possible and indeed the running instances stopped

## Steps to Reproduce

```Python
Python 3.5.2 (default, Nov 12 2018, 13:43:14)
[GCC 5.4.0 20160609] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> from spython.main import Client as client
>>> client.instances()
INSTANCE NAME    PID      IMAGE
instance0        13818    /redacted/alpine_latest.sif

[instance://instance0]
>>> client.instance_stopall()
0
>>> client.instances()
INSTANCE NAME    PID      IMAGE
instance0        13818    /redacted/alpine_latest.sif

[instance://instance0]
>>> client.instance_stopall(sudo=True)
0
>>> client.instances()
INSTANCE NAME    PID      IMAGE
instance0        13818    /redacted/alpine_latest.sif

[instance://instance0]
```

## Context

[provide more detailed introduction to the issue itself . This is for make a reproducible issue.]
* Operating System: Ubuntu16.04
* singularity version:  3.0.1-94.g7de6fa2
* spython version: 0.0.51
* python version: 3.5.2

### PR DESCRIPTION
**Pull request by vsoch**
This pull request will close #86 , fixing the bug with instance stop all.

### CODE REVIEW

**Comment by al3x609** [comment]
lgtm, 
tested code :).

**Comment by vsoch** [comment]
It's going to take me a few cycles to get 3.1 testing on Travis, I need to step away for a bit but I'll be back!

**Comment by vsoch** [comment]
@al3x609 I think your formatting of the version string was not in the right spot, all the tests in the matrix didn't work :/

**Comment by vsoch** [comment]
This is very bad - TravisCI is all over the place. The only consistency is that there are random md5sum check fails and other random errors. Unfortunately this isn't going to be merged any time soon.

**Comment by al3x609** [comment]
ok, WIP, for future, release, tanks @vsoch for your time. :)

**Comment by vsoch** [comment]
I'm restoring to the old version, someone else can address this that warrants needing it.

**Comment by vsoch** [comment]
https://pypi.org/project/spython/0.0.52/

**Pull request merged**
