### PR TITLE
updating install to be included in README

### PR DESCRIPTION
**Pull request by vsoch**
hey @remyd1 is this what you have in mind?

### CODE REVIEW

**Comment by remyd1** [comment]
Absolutely.

However, I would prefer saying `pip3` instead of `pip` or even `python3` instead of `python` because many people have already python2.X and python3.X locally. `python` or `pip` is a symbolic link to the right binary version, but you can't assume which version will be use.
If you know precisely the version needed, you can also specify it.

Kind regards,
Rémy.

**Comment by vsoch** [comment]
all set!

**Comment by remyd1** [comment]
Perfect !

**Comment by vsoch** [comment]
Awesome! Merging.

**Pull request merged**
