### PR TITLE
Add options and writable to exec, shell, run

### LINKED ISSUE #138: --writable option for execute/run not working in spython
## Expected Behavior

I have a sandbox `debian/` built from `debian.sif`.

```
>>> from spython.main import Client as c
>>> c.execute('debian', 'touch /file', writable=True, sudo=True)
{'message': "touch: cannot touch '/file': Read-only file system\n", 'return_code': 1}
```
but on doing the same natively from terminal,

```
sudo singularity exec --writable debian touch /file
```
it works and the file gets created.

## Actual Behavior
```
>>> c.execute('debian', 'touch /file', writable=True, sudo=True)
```
This step should work perfectly same like when done natively.

## Steps to Reproduce

```
sudo singularity build --sandbox debian/ docker://debian:buster-slim
```
Then do the above mentioned steps.
## Context

* Operating System: Ubuntu 16.04
* singularity version: 3.2.0
* spython version: 0.0.71
* python version: 3.7

## Failure Logs

```
{'message': "touch: cannot touch '/file': Read-only file system\n", 'return_code': 1}

[14]+  Stopped                 python
```

### PR DESCRIPTION
**Pull request by vsoch**
This pull request will allow the user to specify a list of options to each of exec, shell, and run, and also if the execution should be `--writable`. I've also updated the documentation (and docstrings) with these examples.

This will close #138

### CODE REVIEW

**Comment by vsoch** [comment]
@JayjeetAtGithub you can test this fix. First, remove all previous spython versions. Do this until it tells you it is installed:

```python
pip uninstall spython
```
Then, clone this branch and install:

```python
git clone -b add/options-writabl  https://github.com/singularityhub/singularity-cli
cd singularity-cli
python setup.py install
```
And then try the commands that were not working for you! I've updated the docs [here](https://github.com/singularityhub/singularity-cli/blob/add/options-writabl/docs/pages/commands-images.md#run-and-exec-options) to show them as well.

**Comment by JayjeetAtGithub** [comment]
@vsoch Thanks a lot! All well now.

**Comment by vsoch** [comment]
Ready to merge?

**Comment by JayjeetAtGithub** [comment]
Yep :smile:

**Comment by vsoch** [comment]
You got it! Please give me a few minutes to release to pypi, I will post the link here when it's done.

**Comment by vsoch** [comment]
https://pypi.org/project/spython/0.0.72/

**Pull request merged**
