### PR TITLE
Adds an optional skip_cmd parameter to convert()

### PR DESCRIPTION
**Pull request by ivotron**
adds an optional parameter to the singularity writer in order to make it optional
to leave out the `CMD` instruction from the runscript.

### CODE REVIEW

**Comment by ivotron** [comment]
hi @vsoch . Would this be something that can be incorporated? I can add tests if needed. Thanks!

**Comment by vsoch** [comment]
Oh this is a great way to think about it (and it works for you I suspect?) One tiny point to discuss - instead of "skip_cmd" with a default to False, why not "include_cmd" with a default to True? The reason is because the original Singularity had this argument, and it nicely mirrors that. (search for IncludeCmd on this page https://singularity.lbl.gov/docs-docker)

**Comment by vsoch** [comment]
Yes, 100% - let me know about what you think of changing the name and direction of the variable, and if we can add a test that would finish up the work. Would it make sense to also provide a flag for the converter run on the command line? E.g.,

```
 spython recipe --skip-cmd
```
And that would set include_cmd to False, and it's default would be False. E.g., 

```python
# default False           # default True
# True == True when we use defaults
not args.skip_cmd == include_cmd
```
for black, you likely will want to run it before pushing again if you change more than a few arguments, and the version matters too - here is the information you need to run locally:

```
pip install black==19.3b0
black spython
```

**Comment by ivotron** [comment]
awesome. thanks a lot for the feedback, I'll work on those 3 things. Thanks!

**Pull request closed without merging**
