### PR TITLE
silence deprecation warnings

### PR DESCRIPTION
**Pull request by MarDiehl**
they show up for:

* re (python 3.9.7)
* semver 2.13.0

### CODE REVIEW

**Comment by vsoch** [comment]
We will probably need to bump the version (in spython/version.py) and add a note to the CHANGELOG (.md) in the root if it's not too much trouble!

**Comment by vsoch** [comment]
Also can you please confirm the changes still work in older versions of Python (3.9.x is fairly new) and that semver here https://github.com/singularityhub/singularity-cli/blob/64358eb33eee6a399461bb0ddeec4951fc01b415/spython/version.py#L17 is set to the minimum that will be allowed with this UI change?

**Comment by MarDiehl** [comment]
I think the most sustainable way to ensure a minimum python version is to parameterize the github actions to use various python versions. I would implement this first in a separate branch if that is ok

**Comment by vsoch** [comment]
If you'd be willing to do that, it would be great.

**Comment by MarDiehl** [comment]
I have a branch that runs the tests with python 3.7-3.9.
Unfortunately, I cannot install singularity on the debian containers and needed to mark some tests as xfail. For most of them, that was a clear task ('singularity not found') but for two I'm not sure:

https://github.com/MarDiehl/singularity-cli/runs/3758070266?check_suite_focus=true

**Comment by vsoch** [comment]
ah I see the issue. We don't run the singularity python tests on GitHub CI - singularity doesn't install there with appropriate permissions to do so. You'll want to add the matrix logic to .circleci/config.yaml.

**Comment by vsoch** [comment]
But I haven't tried it in years - if you want to give a shot in GitHub you could try https://github.com/marketplace/actions/setup-singularity.

**Comment by MarDiehl** [comment]
It almost works: https://github.com/MarDiehl/singularity-cli/runs/3759771046?check_suite_focus=true, there are only two issues
1) `sudo singularity` does not work. If sudo is required, xfail would make sense here. sudo does not exist on all systems anyways
1) A test for a substring should be a test for a substring in a list of lists. This is easy to implement, but I don't understand the consequences for other setups

**Comment by vsoch** [comment]
sudo should work in actions - that failure looks like you need the singularity install location in sudos path. That could be done here or maybe better alongside the action to install it.

**Comment by MarDiehl** [comment]
I've included a workaround:
https://github.com/MarDiehl/singularity-cli/runs/3760571852?check_suite_focus=true

any comments on the remaining fails? I would assume that the extra information `INFO:    Convert SIF file to sandbox...` and `INFO:    Cleaning up image...` is related to some debug settings.

**Comment by vsoch** [comment]
That should be easy to fix! You can add:

```
if isinstance(result['message'], list):
        result['message'] = "".join(result['message'])
```
to test_client.py for the `test_execute_with_return_code` function.

**Review by vsoch — APPROVED** [review]

**Comment by vsoch** [comment]
Thanks again! It looks much better without the warnings.

**Pull request merged**
