### PR TITLE
fixing issue with instances, should return one

### LINKED ISSUE #83: Getting an instance object using client.instances('instance_name') returns list of all instances
## Expected Behavior

using client.instances('name_of_instance') should return an Instance object

[Following Sample from Documentation](https://singularityhub.github.io/singularity-cli/commands-instances#stop)
## Actual Behavior

using client.instances('name_of_instance') should returns list of instances

## Steps to Reproduce

```
>>> from spython.main import Client as client  
>>> client.instances()
INSTANCE NAME    PID      IMAGE
instance0        23991    /redacted/alpine_latest.sif
instance1        24313    /redacted/alpine_latest.sif
>>> myinstance = client.instances('instance0')
INSTANCE NAME    PID      IMAGE
instance0        23991   /redacted/alpine_latest.sif
instance1        24313    /redacted/alpine_latest.sif
>>>print(type(myinstance))
<class 'list'>
>>>myinstance = myinstance[0]
>>>print(type(myinstance))
<class 'spython.instance.Instance'>
```

## Context

[provide more detailed introduction to the issue itself . This is for make a reproducible issue.]
* Operating System: Ubuntu16.04
* singularity version:  3.0.1-94.g7de6fa2
* spython version: 0.0.49
* python version: 3.5.2

### PR DESCRIPTION
**Pull request by vsoch**
This PR will fix the Client.instances() command so that if the user provides a name, a single instance is returned instead of a list. This will close #83

### CODE REVIEW

**Comment by vsoch** [comment]
@al3x609 if you might kindly test the PR here - we want to make sure:
 
 - when more than one instance is running, when you do `Client.instances("myinstance")` (providing a particular name) it returns an instance object (and not a list).
 - the issues with version 2.* checking are fixed here too :)

**Comment by vsoch** [comment]
ok fixed.

**Comment by vsoch** [comment]
@al3x609 ready for merge?

**Comment by vsoch** [comment]
https://pypi.org/project/spython/0.0.51/

**Comment by al3x609** [comment]
👍  :)

**Pull request merged**
