### PR TITLE
WIP: Use pytest for tests

### PR DESCRIPTION
**Pull request by Flamefire**
Using pytest allows for faster writing of tests due to easier syntax as well as including e.g. coverage and other pytest plugins

### CODE REVIEW

**Comment by vsoch** [comment]
hey do you want me to fix the linting issues? Happy to :)

**Comment by Flamefire** [comment]
No it's fine. Marked the PR as WIP because I wanted to try how it works on CI, I'm not yet done.

**Comment by vsoch** [comment]
Alrighty - I'm well into the refactor for the recipes, I'll take the fix for #111

**Comment by Flamefire** [comment]
I'm off till monday. You can take this over to see if you can fix the python2 failure. Not sure why the filter doesn't work there...

**Comment by vsoch** [comment]
You got it! Thanks @Flamefire, enjoy your time off.

**Comment by Flamefire** [comment]
Just got an easy idea: use a pytest decorator to skip this if singularity 2. Then you only need 1 cmd to run all tests.
I suggest you base your changes on this and I'll fix this monday.

**Comment by vsoch** [comment]
okay back in business, home safely! Starting to work on this now.

**Pull request merged**
