### PR TITLE
Changed stdout to None

### PR DESCRIPTION
**Pull request by wkpalan**
Added None type for stdout for run_command function

```
from spython.main import Client
image_loc = Client.pull(image="shub://jekriske/lolcow:lowfat",name="lolcow.simg")
myinstance = Client.instance(image=image_loc,name="lolcow")
print(myinstance)
result = Client.run(myinstance)
```

The above code hangs indefinitely if the stdout=subprocess.PIPE is used in the command.

The subprocess.PIPE method somehow ends up with a buffer fill error and hangs indefinitely for me. Maybe it is a machine issue in Ubuntu. Maybe the output is empty and that could be reason why it hangs.

This issue has been explained in different places like [here](https://www.reddit.com/r/Python/comments/1vbie0/subprocesspipe_will_hang_indefinitely_if_stdout/) and [here](https://thraxil.org/users/anders/posts/2008/03/13/Subprocess-Hanging-PIPE-is-your-enemy/)

### CODE REVIEW

**Comment by vsoch** [comment]
Ah apologies it went off my radar! Could you please provide for me to test:

- a command to run that hangs indefinitely without the fix, and then is fixed with the PR?

As soon as I can test, I can be sure to merge and release a new version on pypi. I do need to test first however :)

**Comment by vsoch** [comment]
So for the current version I have (0.0.39) I am able to do all those commands without anything hanging. For example:

```
from spython.main import Client
image_loc = Client.pull(image="shub://jekriske/lolcow:lowfat",name="lolcow.simg")
singularity pull --name lolcow.simg shub://jekriske/lolcow:lowfat
Progress |===================================| 100.0% 
Done. Container is at: /home/vanessa/Documents/Dropbox/Code/share/repo2docker-jupyterlab/binder/lolcow.simg
lolcow.simg

myinstance = Client.instance(image=image_loc,name="lolcow")
print(myinstance)
   ...: 
instance://lolcow
result = Client.run(myinstance)
 _______________________________________
/ Few things are harder to put up with  \
| than the annoyance of a good example. |
|                 -- "Mark Twain,       |
\ Pudd'nhead Wilson's Calendar"         /
 ---------------------------------------
        \   ^__^
         \  (oo)\_______
            (__)\       )\/\
                ||----w |
                ||     ||
 _______________________________________
/ Few things are harder to put up with  \
| than the annoyance of a good example. |
|                 -- "Mark Twain,       |
\ Pudd'nhead Wilson's Calendar"         /
 ---------------------------------------
        \   ^__^
         \  (oo)\_______
            (__)\       )\/\
                ||----w |
                ||     ||
```
I cannot reproduce this error with the original case that you provided - do you have a different example?

**Comment by wkpalan** [comment]
I am testing the code right now.

**Comment by wkpalan** [comment]
## Operating system tested on
```
Distributor ID:    Ubuntu
Description:    Ubuntu 18.04.1 LTS
Release:    18.04
Codename:    bionic
Python Version:    Python 3.6.5
```
## The commands used for testing the fix
```
from spython.main import Client
instance_name="lolcow"
image_loc = Client.pull(image="shub://jekriske/lolcow:lowfat",name="lolcow.simg")
myinstance = Client.instance(image=image_loc,name=instance_name)
result = Client.run(myinstance)
```

## Before fixing the code
```
Done. Container is at: /mnt/raid/lab_data/tmp/singularity-cli/lolcow.simg
```
The code runs and starts the instance, but hangs right after.

## After fixing the code
```
singularity pull --name lolcow.simg shub://jekriske/lolcow:lowfat
Progress |===================================| 100.0%
Done. Container is at: /mnt/raid/lab_data/tmp/singularity-cli/lolcow.simg
lolcow.simg
 _______________________________________
/ Another such victory over the Romans, \
| and we are undone.                    |
\                 -- Pyrrhus            /
 ---------------------------------------
        \   ^__^
         \  (oo)\_______
            (__)\       )\/\
                ||----w |
                ||     ||
 _______________________________________
/ Another such victory over the Romans, \
| and we are undone.                    |
\                 -- Pyrrhus            /
 ---------------------------------------
        \   ^__^
         \  (oo)\_______
            (__)\       )\/\
                ||----w |
                ||     ||

```

**Comment by wkpalan** [comment]
## Operating system tested on
```
Red Hat Enterprise Linux Server release 7.5 (Maipo)
Python Version:    Python 3.6.3
Singularity Version:    2.4.5-dist
```
## The commands used for testing the fix
```
from spython.main import Client
instance_name="lolcow"
image_loc = Client.pull(image="shub://jekriske/lolcow:lowfat",name="lolcow.simg")
myinstance = Client.instance(image=image_loc,name=instance_name)
result = Client.run(myinstance)
```

## Results before fixing code
```
Progress |===================================| 100.0%
Done. Container is at: /home/kokul/lolcow.simg
lolcow.simg
 ______________________________________
/ Hear about the Californian terrorist \
| that tried to blow up a bus?         |
\ Burned his lips on the exhaust pipe. /
 --------------------------------------
        \   ^__^
         \  (oo)\_______
            (__)\       )\/\
                ||----w |
                ||     ||
 ______________________________________
/ Hear about the Californian terrorist \
| that tried to blow up a bus?         |
\ Burned his lips on the exhaust pipe. /
 --------------------------------------
        \   ^__^
         \  (oo)\_______
            (__)\       )\/\
                ||----w |
                ||     ||
```

**Comment by wkpalan** [comment]
Alternative to this fix if capture=False is used [here](https://github.com/singularityhub/singularity-cli/blob/db78211fe53249d89d39c611d68ab17b75d77ba8/spython/instance/cmd/start.py#L68) then this problem would go away

**Comment by vsoch** [comment]
You will need to provide me with something so I can produce the error (on my machine with the old version) for me to review. As I stated, I can’t reproduce the issue you are having.

**Comment by wkpalan** [comment]
Ok, I'm working on testing in one more machine. If that machine with CentOS 7 runs, then I will just use the main repo. It seems to only affect Ubuntu at this time.

**Comment by wkpalan** [comment]
Can you let me know what OS you are using?

**Comment by vsoch** [comment]
Here are some hypotheses (I have ubuntu 16.04, and I can't reproduce)

 - you already have an instance started with a name, and there is some kind of bug that the client doesn't catch (and it hangs)
 - you are out of disk space
 - you don't have permissions to write an image somewhere
 - the pull has been done too many times and there is some bug with space / naming
 
For all of the above, and **please read this carefully** I need you to **first run the command without any error outside of the spython client** - this means using Singularity on the command line. ONLY then should you try the same command (when you are sure it works with singularity native on the system) using spython. Please confirm that you have read this instruction! :)

**Comment by wkpalan** [comment]
THANK YOU for the effort. I have read your instructions, and I always have **run the commands via terminal** before I tried spython. 

The issues I am having on multiple operating systems are specific to spython.  Below example works for direct commands from command line, but the same commands don't work when I use spython.

OS: CentOS Linux release 7.4.1708 (Core)
Singularity version: 2.5.1-dist

```
#Bash
singularity instance.stop lolcow
singularity pull -n lolcow.simg shub://jekriske/lolcow:lowfat
singularity instance.start lolcow.simg lolcow
singularity run instance://lolcow
singularity instance.stop lolcow
```

```
ERROR: No instances found with the name(s): lolcow
Progress |===================================| 100.0%
Done. Container is at: /pylon5/bc5fp5p/kokul84/sing-test/lolcow.simg
 ________________________________________
/ checkuary, n:                          \
|         The thirteenth month of the    |
| year.  Begins New Year's Day and ends  |
|         when a person stops            |
| absentmindedly writing the old year on |
\ his checks.                            /
 ----------------------------------------
        \   ^__^
         \  (oo)\_______
            (__)\       )\/\
                ||----w |
                ||     ||
Stopping lolcow instance of /pylon5/bc5fp5p/kokul84/sing-test/lolcow.simg (PID=28051)
```
These commands finish within less than 1-2 seconds

```
#Python
from spython.main import Client
image_loc = Client.pull(image="shub://jekriske/lolcow:lowfat",name="lolcow.simg")
instance_name="lolcow"
myinstance = Client.instance(image=image_loc,name=instance_name)
result = Client.run(myinstance)
```

```
singularity pull --name lolcow.simg shub://jekriske/lolcow:lowfat
Done. Container is at: /pylon5/bc5fp5p/kokul84/sing-test/lolcow.simg
lolcow.simg
```

The command starts to hang here, and I have waited for 5-10 minutes for it to complete.

**Comment by vsoch** [comment]
I can't reproduce the hang :(

**Comment by wkpalan** [comment]
I guess I'm going to let this go. I'll ask the testers to clone my fork and install spython from there.

**Comment by vsoch** [comment]
Heyo! I want to help you, but you have to understand the first step to addressing an issue is reproducing it. How can I even test this if I cannot reproduce your issue?

**Comment by vsoch** [comment]
Ok sounds good. Maybe that will help!

**Pull request closed without merging**
